---
  #
  # ansible-playbook -i inventory -l tag_cluster_mon:\&tag_role_ha wavefront-ansible.yml -C --list-hosts


- hosts: all
  become: true
  gather_facts: true
  serial: "{{ serialNumber }}"

  vars:
    - serialNumber: 1

  roles:
    - wavefront.wavefront-ansible
