---
- name: Install Wavefront Proxy (Ubuntu)
  apt:
    name: "{{ wavefront_proxy_pkg }}"
    state: "{{ wavefront_pkg_state }}"
  register: result
  until: result|succeeded
  tags:
   - install
   - debian
   - proxy
